export const books = [
  {
    Author: "Marcel Proust",
    Title: "In Search of Lost Time",
    Pages: 175,
    YOP: 2005,
    BIL: 10,
    SRC: "book1.jpg",
  },
  {
    Author: "James Joyce",
    Title: "Ulysses",
    Pages: 665,
    YOP: 2005,
    BIL: 6,
    SRC: "book2.jpg",
  },
  {
    Author: "Miguel de Cervantes",
    Title: "Don Quixote",
    Pages: 578,
    YOP: 2014,
    BIL: 2,
    SRC: "book3.jpg",
  },
  {
    Author: "Gabriel Garcia Marquez",
    Title: "One Hundred Years of Solitude",
    Pages: 592,
    YOP: 1993,
    BIL: 9,
    SRC: "book4.jpg",
  },
  {
    Author: "F. Scott Fitzgerald",
    Title: "The Great Gatsby",
    Pages: 238,
    YOP: 1991,
    BIL: 6,
    SRC: "book5.jpg",
  },
  {
    Author: "Herman Melville",
    Title: "Moby Dick",
    Pages: 540,
    YOP: 2014,
    BIL: 10,
    SRC: "book6.jpg",
  },
  {
    Author: "Leo Tolstoy",
    Title: "War and Peace",
    Pages: 759,
    YOP: 1994,
    BIL: 5,
    SRC: "book7.jpg",
  },
  {
    Author: "William Shakespeare",
    Title: "Hamlet",
    Pages: 104,
    YOP: 1981,
    BIL: 3,
    SRC: "book8.jpg",
  },
  {
    Author: "Homer",
    Title: "The Odyssey",
    Pages: 147,
    YOP: 1614,
    BIL: 2,
    SRC: "book9.jpg",
  },
  {
    Author: "Gustave Flaubert",
    Title: "Madame Bovary",
    Pages: 618,
    YOP: 2015,
    BIL: 8,
    SRC: "book10.jpg",
  },
  {
    Author: "Dante Alighieri",
    Title: "The Divine Comedy",
    Pages: 452,
    YOP: 1995,
    BIL: 6,
    SRC: "book11.jpg",
  },
  {
    Author: "Vladimir Nabokov",
    Title: "Lolita",
    Pages: 382,
    YOP: 1997,
    BIL: 9,
    SRC: "book12.jpg",
  },
  {
    Author: "Fyodor Dostoyevsky",
    Title: "The Brothers Karamazov",
    Pages: 212,
    YOP: 2004,
    BIL: 7,
    SRC: "book13.jpg",
  },
  {
    Author: "Fyodor Dostoyevsky",
    Title: "Crime and Punishment",
    Pages: 465,
    YOP: 1980,
    BIL: 9,
    SRC: "book14.jpg",
  },
  {
    Author: "Emily Brontë",
    Title: "Wuthering Heights",
    Pages: 325,
    YOP: 2016,
    BIL: 8,
    SRC: "book15.jpg",
  },
  {
    Author: "J. D. Salinger",
    Title: "The Catcher in the Rye",
    Pages: 533,
    YOP: 2016,
    BIL: 1,
    SRC: "book16.jpg",
  },
  {
    Author: "Jane Austen",
    Title: "Pride and Prejudice",
    Pages: 241,
    YOP: 2014,
    BIL: 6,
    SRC: "book17.jpg",
  },
  {
    Author: "Mark Twain",
    Title: "The Adventures of Huckleberry Finn",
    Pages: 479,
    YOP: 2016,
    BIL: 9,
    SRC: "book18.jpg",
  },
  {
    Author: "Leo Tolstoy",
    Title: "Anna Karenina",
    Pages: 264,
    YOP: 2002,
    BIL: 6,
    SRC: "book19.jpg",
  },
  {
    Author: "Lewis Carroll",
    Title: "Alice's Adventures in Wonderland",
    Pages: 581,
    YOP: 1985,
    BIL: 8,
    SRC: "book20.jpg",
  },
  {
    Author: "Homer",
    Title: "The Iliad",
    Pages: 377,
    YOP: 1598,
    BIL: 5,
    SRC: "book21.jpg",
  },
  {
    Author: "Virginia Woolf",
    Title: "To the Lighthouse",
    Pages: 172,
    YOP: 1986,
    BIL: 8,
    SRC: "book22.jpg",
  },
  {
    Author: "Joseph Heller",
    Title: "Catch-22",
    Pages: 719,
    YOP: 2011,
    BIL: 9,
    SRC: "book23.jpg",
  },
  {
    Author: "Joseph Conrad",
    Title: "Heart of Darkness",
    Pages: 112,
    YOP: 1981,
    BIL: 7,
    SRC: "book24.jpg",
  },
  {
    Author: "William Faulkner",
    Title: "The Sound and the Fury",
    Pages: 779,
    YOP: 1995,
    BIL: 8,
    SRC: "book25.jpg",
  },
  {
    Author: "George Orwell",
    Title: "Nineteen Eighty Four",
    Pages: 610,
    YOP: 2008,
    BIL: 1,
    SRC: "book26.jpg",
  },
  {
    Author: "Charles Dickens",
    Title: "Great Expectations",
    Pages: 429,
    YOP: 1999,
    BIL: 5,
    SRC: "book27.jpg",
  },
  {
    Author: "John Steinbeck",
    Title: "The Grapes of Wrath",
    Pages: 330,
    YOP: 2002,
    BIL: 2,
    SRC: "book28.jpg",
  },
  {
    Author: "William Faulkner",
    Title: "Absalom, Absalom!",
    Pages: 228,
    YOP: 2015,
    BIL: 9,
    SRC: "book29.jpg",
  },
  {
    Author: "Ralph Ellison",
    Title: "Invisible Man",
    Pages: 761,
    YOP: 1997,
    BIL: 5,
    SRC: "book30.jpg",
  },
];
